# Generated by Django 3.2.18 on 2023-03-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230328_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
