# Generated by Django 3.2.18 on 2023-04-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
