# Generated by Django 3.2.18 on 2023-04-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_session',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
