# Generated by Django 3.2.18 on 2023-04-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_order_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
